name: fitack
description: "fitness app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  image: assets/images/logo.png
  background_image: "assets/images/background.png"
  android_12:
    image: assets/images/logo.png
    background_image: "assets/images/background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
